CREATE TABLE IF NOT EXISTS patient (
  id INT AUTO_INCREMENT PRIMARY KEY,
  email VARCHAR(255) NOT NULL,
  password VARCHAR(255) NOT NULL,
  id_Card_No VARCHAR(255) NOT NULL,
  first_Name VARCHAR(255) NOT NULL,
  last_Name VARCHAR(255) NOT NULL,
  phone_Number VARCHAR(255) NOT NULL,
  birthday DATE NOT NULL
);



INSERT INTO patient (email,password,id_Card_No,first_Name,last_Name,phone_Number,birthday) VALUES ('seba.r@gmail.com','koty123','435515','Seba','Kowalski','545543252','1999-12-15');
INSERT INTO patient (email,password,id_Card_No,first_Name,last_Name,phone_Number,birthday) VALUES ('marek.k@gmail.com','pomirdo1','65423','Marek','Komarczyk','8765634','2001-11-13');
INSERT INTO patient (email,password,id_Card_No,first_Name,last_Name,phone_Number,birthday) VALUES ('tomek.p@gmail.com','marchew1','654234','tomek','Pawlowski','4326622','12000-09-02');

CREATE TABLE IF NOT EXISTS visit (
id INT AUTO_INCREMENT PRIMARY KEY,
VISIT_TIME TIMESTAMP NOT NULL,
END_VISIT_TIME TIMESTAMP NOT NULL,
FOREIGN KEY (PATIENT_ID) REFERENCES patient(id)
);

INSERT INTO visit (VISIT_TIME,END_VISIT_TIME,PATIENT_ID) VALUES ('2034-12-12T12:00:00','2034-12-12T12:15:00',NULL);
INSERT INTO visit (VISIT_TIME,END_VISIT_TIME,PATIENT_ID) VALUES ('2031-12-12T14:00:00','2031-12-12T14:15:00',1);

CREATE TABLE IF NOT EXISTS doctor (
id INT AUTO_INCREMENT PRIMARY KEY,
EMAIL VARCHAR(255) NOT NULL,
PASSWORD VARCHAR(255) NOT NULL,
FIRST_NAME VARCHAR(255) NOT NULL,
LAST_NAME VARCHAR(255) NOT NULL
);
INSERT INTO doctor(EMAIL,PASSWORD,FIRST_NAME,LAST_NAME) VALUES ('xxx@gmail.com','sss','tomek','kowalski');
INSERT INTO doctor(EMAIL,PASSWORD,FIRST_NAME,LAST_NAME) VALUES ('yyy@gmail.com','ppp','marek','Poznanski');

CREATE TABLE IF NOT EXISTS facility (
id INT AUTO_INCREMENT PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
CITY VARCHAR(255) NOT NULL,
ZIP_CODE VARCHAR(255) NOT NULL,
STREET_NAME VARCHAR(255) NOT NULL,
STREET_NUMBER VARCHAR(255) NOT NULL
);

INSERT INTO facility(NAME,CITY,ZIP_CODE,STREET_NAME,STREET_NUMBER) VALUES ('olsztynska','lodz','94-231','piotrkowska','232');
INSERT INTO facility(NAME,CITY,ZIP_CODE,STREET_NAME,STREET_NUMBER) VALUES ('warszawska','warszawa','32-231','ppoznansa','232');